// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Cancha struct {
	IDCancha             int32     `json:"id_cancha"`
	Nombre               string    `json:"nombre"`
	Precio               string    `json:"precio"`
	Activa               bool      `json:"activa"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
	DuracionTurnoMinutos int16     `json:"duracion_turno_minutos"`
	HoraApertura         time.Time `json:"hora_apertura"`
	HoraCierre           time.Time `json:"hora_cierre"`
	IDInstitucion        int32     `json:"id_institucion"`
	IDDeporte            int32     `json:"id_deporte"`
}

type Deporte struct {
	IDDeporte int32     `json:"id_deporte"`
	Nombre    string    `json:"nombre"`
	Activo    bool      `json:"activo"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Institucion struct {
	IDInstitucion int32     `json:"id_institucion"`
	Nombre        string    `json:"nombre"`
	Direccion     string    `json:"direccion"`
	Telefono      string    `json:"telefono"`
	Email         string    `json:"email"`
	Descripcion   string    `json:"descripcion"`
	Activo        bool      `json:"activo"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	Ciudad        string    `json:"ciudad"`
	Provincia     string    `json:"provincia"`
}
