// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const createCancha = `-- name: CreateCancha :one
INSERT into cancha(nombre,precio,duracion_turno_minutos,hora_apertura,hora_cierre,id_institucion,id_deporte)
VALUES($1, $2, $3, $4, $5, $6,$7)
RETURNING id_cancha, nombre, precio, activa, created_at, updated_at, duracion_turno_minutos, hora_apertura, hora_cierre, id_institucion, id_deporte
`

type CreateCanchaParams struct {
	Nombre               string `json:"nombre"`
	Precio               string `json:"precio"`
	DuracionTurnoMinutos int16  `json:"duracion_turno_minutos"`
	HoraApertura         string `json:"hora_apertura"`
	HoraCierre           string `json:"hora_cierre"`
	IDInstitucion        int32  `json:"id_institucion"`
	IDDeporte            int32  `json:"id_deporte"`
}

func (q *Queries) CreateCancha(ctx context.Context, arg CreateCanchaParams) (Cancha, error) {
	row := q.db.QueryRowContext(ctx, createCancha,
		arg.Nombre,
		arg.Precio,
		arg.DuracionTurnoMinutos,
		arg.HoraApertura,
		arg.HoraCierre,
		arg.IDInstitucion,
		arg.IDDeporte,
	)
	var i Cancha
	err := row.Scan(
		&i.IDCancha,
		&i.Nombre,
		&i.Precio,
		&i.Activa,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DuracionTurnoMinutos,
		&i.HoraApertura,
		&i.HoraCierre,
		&i.IDInstitucion,
		&i.IDDeporte,
	)
	return i, err
}

const createDeporte = `-- name: CreateDeporte :one
INSERT INTO deporte (nombre)
VALUES ($1)
RETURNING id_deporte, nombre, activo, created_at, updated_at
`

func (q *Queries) CreateDeporte(ctx context.Context, nombre string) (Deporte, error) {
	row := q.db.QueryRowContext(ctx, createDeporte, nombre)
	var i Deporte
	err := row.Scan(
		&i.IDDeporte,
		&i.Nombre,
		&i.Activo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInstitucion = `-- name: CreateInstitucion :one
INSERT INTO institucion (
    nombre,
    direccion,
    telefono,
    email,
    descripcion,
    ciudad,
    provincia
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id_institucion, nombre, direccion, telefono, email, descripcion, activo, created_at, updated_at, ciudad, provincia
`

type CreateInstitucionParams struct {
	Nombre      string `json:"nombre"`
	Direccion   string `json:"direccion"`
	Telefono    string `json:"telefono"`
	Email       string `json:"email"`
	Descripcion string `json:"descripcion"`
	Ciudad      string `json:"ciudad"`
	Provincia   string `json:"provincia"`
}

func (q *Queries) CreateInstitucion(ctx context.Context, arg CreateInstitucionParams) (Institucion, error) {
	row := q.db.QueryRowContext(ctx, createInstitucion,
		arg.Nombre,
		arg.Direccion,
		arg.Telefono,
		arg.Email,
		arg.Descripcion,
		arg.Ciudad,
		arg.Provincia,
	)
	var i Institucion
	err := row.Scan(
		&i.IDInstitucion,
		&i.Nombre,
		&i.Direccion,
		&i.Telefono,
		&i.Email,
		&i.Descripcion,
		&i.Activo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ciudad,
		&i.Provincia,
	)
	return i, err
}

const deleteCancha = `-- name: DeleteCancha :execrows
DELETE FROM cancha
WHERE id_cancha = $1
`

func (q *Queries) DeleteCancha(ctx context.Context, idCancha int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCancha, idCancha)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCancha = `-- name: GetCancha :one
SELECT id_cancha,nombre, precio, activa, duracion_turno_minutos, hora_apertura,hora_cierre,id_institucion,id_deporte
FROM cancha
WHERE id_cancha = $1
`

type GetCanchaRow struct {
	IDCancha             int32  `json:"id_cancha"`
	Nombre               string `json:"nombre"`
	Precio               string `json:"precio"`
	Activa               bool   `json:"activa"`
	DuracionTurnoMinutos int16  `json:"duracion_turno_minutos"`
	HoraApertura         string `json:"hora_apertura"`
	HoraCierre           string `json:"hora_cierre"`
	IDInstitucion        int32  `json:"id_institucion"`
	IDDeporte            int32  `json:"id_deporte"`
}

func (q *Queries) GetCancha(ctx context.Context, idCancha int32) (GetCanchaRow, error) {
	row := q.db.QueryRowContext(ctx, getCancha, idCancha)
	var i GetCanchaRow
	err := row.Scan(
		&i.IDCancha,
		&i.Nombre,
		&i.Precio,
		&i.Activa,
		&i.DuracionTurnoMinutos,
		&i.HoraApertura,
		&i.HoraCierre,
		&i.IDInstitucion,
		&i.IDDeporte,
	)
	return i, err
}

const listCanchas = `-- name: ListCanchas :many
SELECT id_cancha,nombre, precio, activa, duracion_turno_minutos, hora_apertura,hora_cierre,id_institucion,id_deporte
FROM cancha
`

type ListCanchasRow struct {
	IDCancha             int32  `json:"id_cancha"`
	Nombre               string `json:"nombre"`
	Precio               string `json:"precio"`
	Activa               bool   `json:"activa"`
	DuracionTurnoMinutos int16  `json:"duracion_turno_minutos"`
	HoraApertura         string `json:"hora_apertura"`
	HoraCierre           string `json:"hora_cierre"`
	IDInstitucion        int32  `json:"id_institucion"`
	IDDeporte            int32  `json:"id_deporte"`
}

func (q *Queries) ListCanchas(ctx context.Context) ([]ListCanchasRow, error) {
	rows, err := q.db.QueryContext(ctx, listCanchas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCanchasRow
	for rows.Next() {
		var i ListCanchasRow
		if err := rows.Scan(
			&i.IDCancha,
			&i.Nombre,
			&i.Precio,
			&i.Activa,
			&i.DuracionTurnoMinutos,
			&i.HoraApertura,
			&i.HoraCierre,
			&i.IDInstitucion,
			&i.IDDeporte,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCanchasActivas = `-- name: ListCanchasActivas :many
SELECT id_cancha,nombre, precio, activa, duracion_turno_minutos, hora_apertura,hora_cierre,id_institucion,id_deporte
FROM cancha
WHERE activa = TRUE
`

type ListCanchasActivasRow struct {
	IDCancha             int32  `json:"id_cancha"`
	Nombre               string `json:"nombre"`
	Precio               string `json:"precio"`
	Activa               bool   `json:"activa"`
	DuracionTurnoMinutos int16  `json:"duracion_turno_minutos"`
	HoraApertura         string `json:"hora_apertura"`
	HoraCierre           string `json:"hora_cierre"`
	IDInstitucion        int32  `json:"id_institucion"`
	IDDeporte            int32  `json:"id_deporte"`
}

func (q *Queries) ListCanchasActivas(ctx context.Context) ([]ListCanchasActivasRow, error) {
	rows, err := q.db.QueryContext(ctx, listCanchasActivas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCanchasActivasRow
	for rows.Next() {
		var i ListCanchasActivasRow
		if err := rows.Scan(
			&i.IDCancha,
			&i.Nombre,
			&i.Precio,
			&i.Activa,
			&i.DuracionTurnoMinutos,
			&i.HoraApertura,
			&i.HoraCierre,
			&i.IDInstitucion,
			&i.IDDeporte,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrecioCancha = `-- name: UpdatePrecioCancha :execrows
UPDATE cancha 
SET precio = $2, updated_at = NOW()
WHERE id_cancha = $1
`

type UpdatePrecioCanchaParams struct {
	IDCancha int32  `json:"id_cancha"`
	Precio   string `json:"precio"`
}

func (q *Queries) UpdatePrecioCancha(ctx context.Context, arg UpdatePrecioCanchaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePrecioCancha, arg.IDCancha, arg.Precio)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
